# Generated by Django 3.1.5 on 2021-01-21 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(blank=True, help_text="Short profile's description", max_length=3000, null=True, verbose_name='resume')),
                ('website', models.URLField(blank=True, max_length=300, null=True, verbose_name='website')),
                ('skill_summary', models.TextField(blank=True, max_length=1000, null=True, verbose_name='summary of skills')),
                ('experience_summary', models.TextField(blank=True, max_length=1000, null=True, verbose_name='summary of experience')),
                ('training_summary', models.TextField(blank=True, max_length=1000, null=True, verbose_name='summary of trainings')),
                ('project_summary', models.TextField(blank=True, max_length=1000, null=True, verbose_name='summary of projects')),
                ('hobbies', models.TextField(blank=True, max_length=1000, null=True, verbose_name='hobbies')),
                ('tags', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Ex: electronics', null=True, size=None, verbose_name='Tags')),
                ('stackoverflow', models.URLField(blank=True, null=True, verbose_name='StackOverflow link')),
                ('github', models.URLField(blank=True, max_length=300, null=True, verbose_name='GitHub link')),
                ('linkedin', models.URLField(blank=True, max_length=100, null=True, verbose_name='LinkedIn link')),
                ('twitter', models.URLField(blank=True, max_length=100, null=True, verbose_name='Twitter link')),
                ('instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='instagram link')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='facebook link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'resumes',
            },
        ),
    ]
