# Generated by Django 3.1.5 on 2022-06-11 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete')], default='PENDING', max_length=25, verbose_name='status')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.attendee')),
            ],
        ),
    ]
