# Generated by Django 3.1.5 on 2022-06-11 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete')], default='PENDING', max_length=25, verbose_name='status')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('courseDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursedate')),
                ('payor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
