# Generated by Django 3.1 on 2020-09-26 02:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=1), blank=True, default=list, help_text='Ex: Arduino', size=None, verbose_name='please add tag'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=1), default=list, help_text='Ex: https://www.site.com/something.pdf', size=None, verbose_name='please add link'),
        ),
    ]
