# Generated by Django 3.1 on 2020-10-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200929_0432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedate',
            options={'get_latest_by': 'date', 'verbose_name_plural': 'Course Dates'},
        ),
    ]
