# Generated by Django 3.1 on 2020-10-30 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20200929_0432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedate',
            options={'get_latest_by': 'date', 'verbose_name_plural': 'Course Dates'},
        ),
        migrations.AlterField(
            model_name='coursedate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
