# Generated by Django 3.1 on 2020-09-26 03:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200926_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None), blank=True, help_text='Ex: https://www.site.com/something.pdf', null=True, size=None, verbose_name='please add link'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='tags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, help_text='Ex: Arduino', null=True, size=None, verbose_name='please add tag'),
        ),
    ]
