# Generated by Django 3.1.5 on 2022-06-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True, help_text='duration in hours', null=True, verbose_name='duration in hours'),
        ),
        migrations.CreateModel(
            name='WhatYoullLearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Structure de donnée Java', max_length=255, verbose_name='title')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wyl', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Introduction', max_length=255, verbose_name='title')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='courses.course')),
            ],
        ),
    ]
