# Generated by Django 3.1.5 on 2022-06-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220608_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_included',
        ),
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.BooleanField(default=False, verbose_name='certification'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='content',
            field=models.TextField(help_text='content', null='True', verbose_name='content'),
            preserve_default='True',
        ),
    ]
