# Generated by Django 3.1 on 2020-11-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201105_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseDates', to='courses.course', verbose_name='course'),
        ),
    ]
