# Generated by Django 3.1.5 on 2022-06-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220608_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedate',
            options={'get_latest_by': 'start_date', 'verbose_name_plural': 'Course Dates'},
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='coursedate',
            name='date',
        ),
        migrations.AddField(
            model_name='attendee',
            name='start_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursedate', verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='coursedate',
            name='end_date',
            field=models.DateTimeField(max_length=255, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='coursedate',
            name='start_date',
            field=models.DateTimeField(max_length=255, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='whatyoulllearn',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatyoulls', to='courses.course'),
        ),
    ]
