# Generated by Django 3.1.5 on 2022-06-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220608_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedate',
            options={'get_latest_by': 'end_date', 'verbose_name_plural': 'Course Dates'},
        ),
        migrations.AlterField(
            model_name='attendee',
            name='start_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursedate', verbose_name='start date'),
        ),
    ]
