# Generated by Django 3.1.5 on 2022-06-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20220611_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='start_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursedate', verbose_name='start date'),
        ),
    ]
