# Generated by Django 3.1.5 on 2022-06-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20220611_1840'),
        ('moncash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetransaction',
            name='courseDate',
        ),
        migrations.AlterField(
            model_name='coursetransaction',
            name='payor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.attendee'),
        ),
    ]
