# Generated by Django 3.1.5 on 2022-06-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220611_1856'),
        ('moncash', '0002_auto_20220611_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetransaction',
            name='payor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.attendee'),
        ),
    ]
