# Generated by Django 3.1 on 2020-11-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
